version: '3.8'

# Services to enable
services:
  # Postgres Database
  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nyc_taxi
    volumes:
      - data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  # PGAdmin console
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    depends_on:
      - postgres

# Volumes to mount
volumes:
  data:
    driver: local
    driver_opts:
      device: ${PWD}/data
      o: bind
      type: none